services:
    video-formatter:
        container_name: ${PROJECT_NAME}-video-formatter
        env_file:
            - .env.local
        build:
            dockerfile: ./Dockerfile
            args:
                SERVICE_PORT: 5000
                SERVICE_NAME: video-formatter
        restart: unless-stopped
        networks:
            - api_network
        volumes:
            - ./:/app
        command: celery -A src.main.celery worker --loglevel=info --queues=api_to_video_formatter
        ports:
            - "5004:5000"

networks:
  api_network:
    name: api_network
    driver: bridge
